services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - SECRET_KEY=change-me-in-production-please
      - POSTGRES_DB=onepiece
      - POSTGRES_USER=onepiece
      - POSTGRES_PASSWORD=onepiece
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - EMAIL_HOST=mail
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=0
      - ACCOUNT_DEFAULT_HTTP_PROTOCOL=http
      - SITE_DOMAIN=localhost:8000
      - VAPID_PUBLIC_KEY=BPaSBaFlwrQIDIfTmBGhzcTthtElSFizvp0hOOwhCpcX77jKsp6Nb-OESquJM7r3_VlCTKieICUBrjt-hseeX5Q
      - VAPID_PRIVATE_KEY=U9ouG837ClfimAoiJwPq8lPK92KEZBEZ_DYX0jxz4Cs
      - VAPID_CLAIM_EMAIL=mailto:your-email@example.com
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_started
    restart: unless-stopped

  mail:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=onepiece
      - POSTGRES_USER=onepiece
      - POSTGRES_PASSWORD=onepiece
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onepiece"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
