# Generated by Django 6.0.3 on 2026-03-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_logo_to_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Hex color for the card border/accent (e.g. #e63946).', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='event_type',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('COMPETITIVE', 'Competitive'), ('CHAMPIONSHIP', 'Championship'), ('DRAFT', 'Draft'), ('OTHER', 'Other')], default='CASUAL', help_text='The type of event.', max_length=15),
        ),
    ]
