# Generated by Django 6.0.3 on 2026-03-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_logo_to_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='location_name',
            field=models.CharField(blank=True, help_text='Venue name or address (visible only to logged-in users).', max_length=300),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location_url',
            field=models.URLField(blank=True, help_text='Link to a map or venue page (e.g. Google Maps URL).'),
        ),
    ]
