# Generated by Django 5.1.15 on 2026-03-05 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_match_wins", models.PositiveIntegerField(default=0)),
                ("total_match_losses", models.PositiveIntegerField(default=0)),
                ("total_match_draws", models.PositiveIntegerField(default=0)),
                ("tournaments_played", models.PositiveIntegerField(default=0)),
                ("tournaments_won", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tournaments_won", "-total_match_wins"],
            },
        ),
    ]
