# Generated by Django 5.1.15 on 2026-03-05 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='The user who invited this player.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited', to=settings.AUTH_USER_MODEL),
        ),
    ]
